### ISSUE TITLE
Create a npm package

### ISSUE THREAD

**Issue by roman-16** [kulakowka/react-bulma#2]
Please create a npm package.

**Comment by kulakowka** [comment]
@Wavum Thank you for your interest in my project. It's not finished yet. I will publish it in npm as soon as it is completed. If you want, you can use a similar project [re-bulma](https://github.com/bokuweb/re-bulma).

**Comment by Thebigbignooby** [comment]
what is the motivation for creating a seperate project instead of contributing to the similar project ?

**Comment by kulakowka** [comment]
@Thebigbignooby I began to do it before I found similar ones.
