### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by casieber** [kulakowka/react-bulma#21]
Currently there is no license file in the repo, meaning that the work is by default under exclusive copyright. [[source](https://choosealicense.com/no-license/)]

You can use the GitHub created [choosealicense.com](https://choosealicense.com/) to help you pick an appropriate license.

Otherwise, if you purposefully left out a license, please add a note to the README saying so.

**Comment by kulakowka** [comment]
I created a PR to fix it https://github.com/kulakowka/react-bulma/pull/22
