### ISSUE TITLE
Document has typo

### ISSUE THREAD

**Issue by masayannuu** [kulakowka/react-bulma#25]
Thank you for Good component!
I notice this document has typo so I open this issue.

https://kulakowka.github.io/react-bulma/#subtitle  

Component of "SubTitle" has been exported as "SubTitle". However, the document is written as "Subtitle" as below.   

`import { Subtitle } from 'reactbulma'`  

"t" in Title must be in uppercase letters.

**Comment by kulakowka** [comment]
I have fixed it. Thank you @masayannuu.
