### ISSUE TITLE
Consider to use classnames package for create a class

### ISSUE THREAD

**Issue by kresli** [kulakowka/react-bulma#5]
currently you are creating classes with `if` statements. I think it would be much easier to use https://www.npmjs.com/package/classnames module. I'm happy to help with it.

**Comment by kulakowka** [comment]
@kresli Yes, I use this package in my other projects. Let's use it here.

**Comment by kulakowka** [comment]
@Julian-B90 what do you think about it? I thought it over. I think we should avoid using unnecessary dependencies.

**Comment by Julian-B90** [comment]
@kulakowka i think classnames was a good module for react-bulma. We use it in our company projects.

**Comment by Julian-B90** [comment]
@kresli maybe you can made a fork and help us with the rebuild with classnames?
I have start with Button https://github.com/kulakowka/react-bulma/blob/master/src/components/Button/Button.js

**Comment by kulakowka** [comment]
@Julian-B90 I will do all the other components.

**Comment by kulakowka** [comment]
[completed](https://github.com/kulakowka/react-bulma/commit/26d3d616de3d66970f9624fb9a00a9924fd72a44)
